-- export-schema.sql  (security item 15: keep the repository able to rebuild the database)
--
-- WHY: db/ starts at migration 023; the original tables and base security rules
-- (001-022) were created before migrations were kept, and Supabase's own
-- migration history lists only some of what was run. The repository alone
-- therefore cannot rebuild the database. This script regenerates the whole
-- STRUCTURE of the public schema from the live catalog as ordinary SQL:
--   sequences, tables, keys and checks, foreign keys, indexes, row-level
--   security switches, functions (with their EXECUTE grants), triggers,
--   policies, table grants and the scheduled cleanup job.
--
-- HOW: run it in the Supabase SQL editor. It returns one row per statement, in
-- a safe order. Export the result (CSV or "copy") and save the "ddl" column as
-- db/schema-snapshot-YYYY-MM-DD.sql. Do this after every batch of migrations
-- and before every demo or defence.
--
-- WHAT IT IS NOT: a backup. It holds no data (accounts, grades, requests). For
-- data see docs/SECURITY-OPERATIONS.md (Supabase backups / a manual export).
-- Things Supabase manages itself are left out on purpose: the auth, storage and
-- extensions schemas, edge function code (kept in supabase/functions/) and
-- project secrets.
--
-- To use a snapshot on an EMPTY project: enable the extensions listed in the
-- header comment, run the snapshot once, then deploy the edge functions and set
-- their secrets.

with
hdr as (
  select 0 as sec, ''::text as k1, 0::bigint as k2,
    '-- CurricuLogic schema snapshot, generated ' || to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI') || E' UTC\n' ||
    '-- extensions in use: ' || (select string_agg(extname, ', ' order by extname) from pg_extension) || E'\n' ||
    'set check_function_bodies = false;' as stmt
),
seqs as (
  select 10, c.relname::text, 0::bigint,
    format('create sequence if not exists public.%I as %s start with %s increment by %s minvalue %s maxvalue %s cache %s%s;',
           s.sequencename, s.data_type, s.start_value, s.increment_by, s.min_value, s.max_value, s.cache_size,
           case when s.cycle then ' cycle' else '' end)
  from pg_sequences s
  join pg_class c on c.relname = s.sequencename and c.relnamespace = 'public'::regnamespace
  where s.schemaname = 'public'
    and not exists (select 1 from pg_depend d
                    where d.objid = c.oid and d.classid = 'pg_class'::regclass and d.deptype = 'i')   -- not an identity column's own sequence
),
tbls as (
  select 20, c.relname::text, 0::bigint,
    'create table public.' || quote_ident(c.relname) || E' (\n' ||
    (select string_agg(
        '    ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || case a.attidentity when 'a' then ' generated always as identity'
                              when 'd' then ' generated by default as identity' else '' end
        || case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
                when d.adbin is not null and a.attidentity = '' then ' default ' || pg_get_expr(d.adbin, d.adrelid)
                else '' end
        || case when a.attnotnull then ' not null' else '' end,
        E',\n' order by a.attnum)
     from pg_attribute a
     left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
     where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)
    || E'\n);'
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind = 'r' and not c.relispartition
),
cons as (
  select 30, c.relname::text, 0::bigint,
         format('alter table public.%I add constraint %I %s;', c.relname, k.conname, pg_get_constraintdef(k.oid))
  from pg_constraint k join pg_class c on c.oid = k.conrelid
  where k.connamespace = 'public'::regnamespace and k.contype in ('p', 'u', 'c', 'x')
),
fks as (
  select 35, c.relname::text, 0::bigint,
         format('alter table public.%I add constraint %I %s;', c.relname, k.conname, pg_get_constraintdef(k.oid))
  from pg_constraint k join pg_class c on c.oid = k.conrelid
  where k.connamespace = 'public'::regnamespace and k.contype = 'f'
),
idx as (
  select 40, t.relname::text, 0::bigint, pg_get_indexdef(ix.indexrelid) || ';'
  from pg_index ix join pg_class t on t.oid = ix.indrelid
  where t.relnamespace = 'public'::regnamespace
    and not exists (select 1 from pg_constraint k where k.conindid = ix.indexrelid)   -- keys already created above
),
rls as (
  select 50, c.relname::text, 0::bigint,
         'alter table public.' || quote_ident(c.relname) || ' enable row level security;'
         || case when c.relforcerowsecurity then ' alter table public.' || quote_ident(c.relname) || ' force row level security;' else '' end
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind = 'r' and c.relrowsecurity
),
fn as (
  select 60, p.proname::text, p.oid::bigint, pg_get_functiondef(p.oid) || ';'
  from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prokind = 'f'
),
fng as (
  -- The signature is written out with its schema: casting the oid to regprocedure
  -- leaves the schema off whenever it is on the search path, which would aim these
  -- statements at the wrong copy of the function.
  select 65, p.proname::text, p.oid::bigint,
         format('revoke all on function public.%I(%s) from public, anon, authenticated, service_role;',
                p.proname, pg_get_function_identity_arguments(p.oid))
         || coalesce((select string_agg(format(' grant execute on function public.%I(%s) to %s;',
                                               p.proname, pg_get_function_identity_arguments(p.oid), r), '' order by r)
                      from unnest(array['anon', 'authenticated', 'service_role']) r
                      where has_function_privilege(r, p.oid, 'execute')), '')
  from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prokind = 'f'
),
trg as (
  select 70, c.relname::text, 0::bigint, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t join pg_class c on c.oid = t.tgrelid
  where c.relnamespace = 'public'::regnamespace and not t.tgisinternal
),
pol as (
  select 80, p.tablename::text, 0::bigint,
         format('create policy %I on public.%I as %s for %s to %s%s%s;',
                p.policyname, p.tablename, lower(p.permissive), lower(p.cmd), array_to_string(p.roles, ', '),
                case when p.qual is not null then ' using (' || p.qual || ')' else '' end,
                case when p.with_check is not null then ' with check (' || p.with_check || ')' else '' end)
  from pg_policies p where p.schemaname = 'public'
),
tgr as (
  select 90, c.relname::text, 0::bigint,
         'revoke all on public.' || quote_ident(c.relname) || ' from anon, authenticated, service_role;'
         || coalesce((select string_agg(format(' grant %s on public.%I to %s;', x.privs, c.relname, x.r), '' order by x.r)
                      from (select r, string_agg(pr, ', ' order by pr) as privs
                            from unnest(array['anon', 'authenticated', 'service_role']) r
                            cross join unnest(array['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'REFERENCES', 'TRIGGER']) pr
                            where has_table_privilege(r, c.oid, pr)
                            group by r) x), '')
  from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind = 'r'
),
cr as (
  select 95, j.jobname::text, 0::bigint, format('select cron.schedule(%L, %L, %L);', j.jobname, j.schedule, j.command)
  from cron.job j
)
select stmt as ddl
from (
  select * from hdr  union all select * from seqs union all select * from tbls union all select * from cons
  union all select * from fks union all select * from idx union all select * from rls union all select * from fn
  union all select * from fng union all select * from trg union all select * from pol union all select * from tgr
  union all select * from cr
) u(sec, k1, k2, stmt)
order by sec, k1, k2;
